name: Build and Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Lambda function
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          cd sam_lambda/CouchQuest
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Build Lambda function using SAM CLI
        id: sam_build
        run: |
          cd sam_lambda/CouchQuest
          sam build

  deploy:
    name: Deploy Lambda function to AWS
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production
      url: ${{ steps.deploy.outputs.web_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Deploy Lambda with SAM CLI
        run: |
          cd sam_lambda/CouchQuest
          sam deploy --no-confirm-changeset --stack-name CouchQuest --capabilities CAPABILITY_IAM || echo "No changes detected, skipping deployment."

      - name: Output deployment status
        id: deploy
        run: |
          echo "Lambda function deployment process finished."