name: Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker images
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          
          docker build -t didrichsen/java-sqs-client:0.1-${COMMIT_HASH} .
          docker tag didrichsen/java-sqs-client:0.1-${COMMIT_HASH} didrichsen/java-sqs-client:latest

      - name: Push Docker images
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          
          docker push didrichsen/java-sqs-client:0.1-${COMMIT_HASH}
          docker push didrichsen/java-sqs-client:latest