name: Plan and Apply with Terraform

on:
  push:
    branches:
      - '*'  # Trigger on all branches

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.9.1

    - name: Terraform Init
      run: terraform init
      working-directory: infra

    # Terraform Plan (for branches other than main)
    - name: Terraform Plan
      if: github.ref != 'refs/heads/main'
      run: terraform plan
      working-directory: infra

    # Terraform Apply (for main branch only)
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve
      working-directory: infra
